Feature/mob 2006 jwt mobile auth management
Iterable/iterable-android-sdk pull request #265
Opened 2020-09-15 19:41 UTC by davidtruong

WIP 

Jwt auth management: https://iterable.quip.com/ZtIfAqGabyXT/Mobile-Auth-Management-Updates

2020-09-23 17:48 UTC, vbabenkoru requested changes
@davidtruong It seems like it will request a new token multiple times in parallel if multiple network calls fail in sequence. I think it should only request once and wait until it completes before spawning new requests.

2020-09-23 20:14 UTC, vbabenkoru requested changes

2020-09-23 20:14 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterablePushRegistration.java
> +                            iterablePushRegistrationData.priorAuthToken
I think we should just store `authToken` with email and userId everywhere in this class, to keep it more consistent. Basically, if we're being passed `email` and `userId`, `authToken` should also be there, because it is tightly coupled with email and userId.

2020-09-23 20:14 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterablePushRegistration.java
> +                        }, null, priorAuthToken);
We're using `iterablePushRegistrationData` to get the email/userId. Passing `priorAuthToken` should not be necessary since it's also available in `iterablePushRegistrationData`.

2020-09-25 14:52 UTC, davidtruong commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> -        if (_email != null && _email.equals(email)) {
I removed it so that we would require a single place to fetch the auth token for maintainability. However thinking about it more, having this in there should be fine since it achieves the same behavior and we call will call the same setAuthToken function which should handle all of the expirations.

2020-09-25 14:52 UTC, davidtruong commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +        _authToken = authToken;
We should be able to do a check for authToken and not set it or call storeAuthData. However we will still need to call onLogIn.

2020-09-25 14:52 UTC, davidtruong commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +                    onSetAuthToken(authToken);
Makes sense, this is unnecessary now since the implementation of requestNewAuthToken is now asynchronous.

2020-09-25 15:25 UTC, davidtruong commented on iterableapi/src/main/java/com/iterable/iterableapi/IterablePushRegistration.java
> +                        }, null, priorAuthToken);
Ah yes, I missed that, Good catch.

2020-09-25 16:26 UTC, davidtruong commented
> @davidtruong It seems like it will request a new token multiple times in parallel if multiple network calls fail in sequence. I think it should only request once and wait until it completes before spawning new requests.

Actually It won't request multiple tokens in parallel. The logic in IterableAuthManager.requestNewAuthToken takes in a hasFailedPriorAuth flag. If this is set from an earlier failed Iterable api call w/ an auth error, then it won't attempt to make a second request to onAuthTokenRequested. 

EX: 2 api requests to the backend in parallel (A, B)
A returns a 401 auth
A triggers requestNewAuthToken with hasFailedPriorAuth = true
A triggers onAuthTokenRequested
B returns a 401 auth
B triggers requestNewAuthToken with hasFailedPriorAuth = true
At this point since the AuthManager's hasFailedPriorAuth is also true, B will not trigger a new onAuthTokenRequested

LMK if you see any issues with this or if you were thinking about a different use case.

2020-09-25 17:20 UTC, davidtruong commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> -        if (_email != null && _email.equals(email)) {
What do you think would be the benefit of having this call signature? When a new token requested from our SDK via `onAuthTokenRequested`, they would need to implement that handler as well.

2020-09-28 06:13 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> -        if (_email != null && _email.equals(email)) {
Oh, I meant the checks that'd skip if the email is the same as it is, etc. Without those, it triggers token refresh and login code every time `setEmail` is called, even if the email didn't change.

2020-09-28 06:17 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> -        if (_email != null && _email.equals(email)) {
The current version calls `onLogOut` even if the email/userId hasn't changed, triggering `disableDevice` call.

2020-09-28 17:20 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableAuthManager.java
> +    public void requestNewAuthToken(boolean hasFailedPriorAuth) {
@davidtruong It seems like it will request a new token multiple times in parallel if multiple network calls fail in sequence. I think it should only request once and wait until it completes before spawning new requests.

2020-09-28 17:22 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableRequest.java
> +                        IterableApi.getInstance().getAuthManager().resetFailedAuth();
What is this line for? Looks like it's only going to be executed if `error == null` and `requestResult.length < 0`, which will never be `true`.

2020-09-28 18:09 UTC, davidtruong commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableAuthManager.java
> +    public void requestNewAuthToken(boolean hasFailedPriorAuth) {
On receiving a 401 from the backend. the network calls should all call the same authManager which should have the same reference to the hasFailedPriorAuth flag, so it should skip additional calls to onAuthTokenRequested. LMK if I'm not understanding your concern correctly.

2020-09-28 18:10 UTC, davidtruong commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableRequest.java
> +                        IterableApi.getInstance().getAuthManager().resetFailedAuth();
Ah, missed the case statement above for the success for error ==null and equestResult.length() > 0.

2020-09-28 18:14 UTC, davidtruong commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableAuthManager.java
> +                    api.getAuthManager().requestNewAuthToken(false);
This should be fine since a majority the functionality in `requestNewAuthToken` runs in a background thread as well.

2020-09-28 18:24 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableAuthManager.java
> +    public void requestNewAuthToken(boolean hasFailedPriorAuth) {
Hm, yeah, you're right, but I've seen two parallel calls to `requestNewAuthToken`. Refreshes from requests have a limit of 1 at a time, but anything that calls with `hasFailedPriorAuth = false` will result in multiple parallel requests. Since those are asynchronous, there is no guarantee of ordering. A call that was triggered first might return last and vice versa.

2020-09-28 19:36 UTC, davidtruong commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableAuthManager.java
> +    public void requestNewAuthToken(boolean hasFailedPriorAuth) {
Gotcha, that makes sense for the non-401 case for standard initialization: setEmail + registerForPush + getMessages. I'll add back in the pending auth flag to skip to restrict simultaneous the calls.

2020-09-29 20:47 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +            getAuthManager().requestNewAuthToken(false);
Do we need to request a new token if the email stays the same?

2020-09-29 20:48 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +            getAuthManager().requestNewAuthToken(false);
There are very likely some apps that call `setEmail` on every app launch. This will cause it to re-request the token on every launch.

2020-09-29 20:55 UTC, davidtruong commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +            getAuthManager().requestNewAuthToken(false);
I'm fine with removing this call if the email is the same as the stored _email. However are there any alternatives for re-requesting a new auth token manually from the app without changing the email?

2020-09-29 23:06 UTC, vbabenkoru commented
@davidtruong Looks like one of the tests is failing.

2020-09-29 23:33 UTC, davidtruong commented
@vbabenkoru Looks like a flaky test. I'll remove it for when we finish fixing the unit tests.

2020-09-30 00:23 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableAuthManager.java
> +                            IterableApi.getInstance().setAuthToken(authToken);
Thinking if checking email/userId exists can help before assigning the authToken can avoid situation where 
1. Valid setEmail was called with email xyz.
2. setEmail (null) got called before getting response to previous one.

By the time we get response, email could be set to null and we would have received a auth token.

Saw the test failure and thought could this be a case?

2020-09-30 20:57 UTC, vbabenkoru approved these changes

2020-10-01 00:40 UTC, merged

2020-10-09 00:29 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +            onLogIn();
We should not be calling `onLogIn()` if it's just a token refresh and the email/userId did not change.

2020-10-09 00:30 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +            if (_authToken != authToken) {
This is doing object comparison instead of string comparison, this will be `false` for identical strings if they're not the _same object_.