[MOB-2146] Enable Java 8 support, migrate to lambdas
Iterable/iterable-android-sdk pull request #267
Opened 2020-09-24 04:32 UTC by vbabenkoru

2020-09-25 22:18 UTC, Ayyanchira reviewed
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/22951141/94320249-57402480-ff41-11ea-98ee-f5908f63ff18.png">

@vbabenkoru , I tried to ran the project on my regular setting . Is there something I should change?

2020-09-29 17:38 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
> +        dialog.setOnCancelListener(dialog1 -> {
`dialog1` was unintentional it seems

2020-09-29 21:35 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +                    (reason, data) -> IterableLogger.e(TAG, "Error while checking deferred deep link: " + reason + ", response: " + data));
Wow.. good to see multiple overriding functions can be written like this... 👍

2020-09-29 21:36 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +                    () -> registerDeviceToken(email, userId, applicationName, deviceToken, null, deviceAttributes)
Whats the convention?
`() ->` should be above this line right?

2020-09-29 21:37 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +                    () -> registerDeviceToken(email, userId, applicationName, deviceToken, null, deviceAttributes)
Actually may be not for single lines

2020-09-29 21:46 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
> +        dialog.setOnCancelListener(dialog1 -> {
```suggestion
        dialog.setOnCancelListener(dialog -> {
```

2020-09-29 21:48 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +                    () -> registerDeviceToken(email, userId, applicationName, deviceToken, null, deviceAttributes)
```suggestion
            final Thread registrationThread = new Thread(() ->
                    registerDeviceToken(email, userId, applicationName, deviceToken, null, deviceAttributes)
```

2020-09-29 21:54 UTC, Ayyanchira requested changes
Added little suggestions

2020-10-14 03:33 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
> +        dialog.setOnCancelListener(dialog1 -> {
This would clash with the other `dialog` defined in the scope...

2020-10-14 03:34 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +                    () -> registerDeviceToken(email, userId, applicationName, deviceToken, null, deviceAttributes)
Fixed

2020-10-28 20:40 UTC, vbabenkoru commented
This might require changes on customer side, so I'm going to close this for now.

2020-10-28 20:40 UTC, closed without merging