Feature/mob 2054 in app animation poc
Iterable/iterable-android-sdk pull request #268
Opened 2020-10-09 05:54 UTC by Ayyanchira

2020-10-13 17:27 UTC, vbabenkoru requested changes
Nice work! Left some comments.
Please add the new payload to `inapp_payload_multiple.json` to make sure we're testing serialization/deserialization of those new fields.

2020-10-13 17:27 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
> +    private static final String INAPP_SHOULD_ANIMATE = "shouldAnimate";
Formatting is different in this value (starts with a lowercase letter).

2020-10-13 17:27 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppMessage.java
> +import static com.iterable.iterableapi.IterableConstants.ITERABLE_IN_APP_BGCOLOR;
Use `IterableConstants.*` instead of importing every constant statically.

2020-10-13 17:27 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppMessage.java
> +    public static class InAppDisplaySetting {
The field is called `inAppDisplaySettings` (plural).

2020-10-13 17:27 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppMessage.java
> +//        String bgColorInHex = "#00D3D3D3";
Looks like something temporary.

2020-10-13 17:27 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppMessage.java
> +        JSONObject bgColorSetting = inAppDisplaySettingsJson.optJSONObject(ITERABLE_IN_APP_BGCOLOR);
To match the convention used in this method, I'd name it `bgColorJson`.

2020-10-13 17:27 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppMessage.java
> +        InAppDisplaySetting inAppDisplaySetting = new InAppDisplaySetting(shouldAnimate, new InAppBgColor(bgColorInHex, bgAlpha));
If there is no `bgColor` in the payload, do we want to create an `InAppBgColor` with null values? It might be better to not create one and just pass `null`.

2020-10-13 17:27 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableWebViewClient.java
> +    void showWebView() {
A `WebViewClient` ideally should not know anything about the view hierarchy.. As I mentioned in an earlier comment, it is probably better to move it up to the `*HTMLNotification` class.

2020-10-13 17:27 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableWebViewClient.java
> +enum InAppLayout {
👍
I'd also move this up to the in-app html notification class since that is where we manage the layout.

2020-10-13 18:17 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppMessage.java
> +        String bgHexColor;
InAppBgColor isn't actually used yet for background color, right?

2020-10-13 22:58 UTC, Ayyanchira commented on iterableapi/src/main/res/anim/bottom_exit.xml
> +    android:duration="500" />
Agreed

2020-10-13 23:00 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppMessage.java
> +        String bgHexColor;
Yes, it is used.. In createInstance of IterableInAppFragmentHTMLNotification.

2020-10-13 23:03 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppMessage.java
> +//        String bgColorInHex = "#00D3D3D3";
Yes.. kept their for test convenience... Easy to uncomment and see in app animation working..
Will remove it too

2020-10-14 23:46 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
> +                            window.setBackgroundDrawable(new ColorDrawable(Color.parseColor(inAppBackgroundColor)));
We'll get a `IllegalArgumentException` if the color string is invalid here.. Can it possibly be invalid?

2020-10-15 12:13 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
> +                            window.setBackgroundDrawable(new ColorDrawable(Color.parseColor(inAppBackgroundColor)));
We would only get hex strings which should be passed from UI.. probably from a color selection..Shouldnt go wrong.. However, we can default it to transparent though if at all error occurs

2020-10-19 19:50 UTC, vbabenkoru commented on app/src/androidTest/java/com/iterable/iterableapi/MainActivityTest.java
> +        waitFor(500);
Hmm wondering if it's possible to replace these delays with something else..

2020-10-19 19:50 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java
> +    public static final int ITERABLE_IN_APP_ANIMATION_DURATION           = 500;
Do you want to keep the duration here or move to xml? I think either option is valid.

2020-10-19 19:51 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableConstants.java
> +    public static final int ITERABLE_IN_APP_ANIMATION_DURATION           = 500;
Yeah.. lets keep it here..

2020-10-19 19:51 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
> +    //TODO: To delete this variable in future iterations
Is anything preventing us from removing it now? (Not necessarily in this PR)

2020-10-19 19:54 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
> +        } else if (getInAppLayout(insetPadding) != InAppLayout.TOP) {
If we're converting padding to `InAppLayout` here anyway, I think it's better to also replace the condition 2 lines above that is still using `insetPadding`.

2020-10-19 19:55 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
> +            dialog.getWindow().setFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS, WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
Why are we only setting this if it's centered or bottom?

2020-10-19 19:56 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
> +    //TODO: To delete this variable in future iterations
We were skeptical if backend would ever send that value. But now that we know nothing had been implemented on backend side to send any old backgroundAlpha values, we can delete it right away.. But just to be safe not this time.

2020-10-19 19:56 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
> +        if (shouldAnimate && (inAppBackgroundColor != null)) {
Background color is dependent on `shouldAnimate` being enabled. Is that what we want?

2020-10-19 19:58 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
Does this mean we don't animate on Android 4.2 and lower?

2020-10-19 20:00 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
> +            dialog.getWindow().setFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS, WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
If we do translucent status for TOP, there is a small overlap of in app content and status bar which we discussed earlier. So to avoid that, TOP in apps will have opaque status bar with content starting right after it

2020-10-19 20:01 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
> +        if (shouldAnimate && (inAppBackgroundColor != null)) {
I did mentioned it on Slab.. will followup on it urgently

2020-10-19 20:02 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppMessage.java
> +    public static class InAppDisplaySettings {
Hmm, if we store padding values within `inAppDisplaySettings`, maybe it makes sense to move the padding values here as well? (Not necessarily within this PR)

2020-10-19 20:07 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
> +            dismissWebviewRunnable.run();
```suggestion
            webView.postDelayed(dismissWebviewRunnable, 400);
```

2020-10-19 20:09 UTC, vbabenkoru commented on iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppMessageTest.java
> +                assertEquals((Boolean) inAppDisplaySettings.get("shouldAnimate"), true);
`assertTrue`?

2020-10-19 20:18 UTC, vbabenkoru commented on iterableapi/src/test/java/com/iterable/iterableapi/IterableInAppMessageTest.java
> +                assertEquals((Boolean) inAppDisplaySettings.get("shouldAnimate"), true);
Actually, you don't need any new code in this file.

2020-10-19 21:05 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
> +            dialog.getWindow().setFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS, WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
I think it'd be helpful to add a comment here explaining this, so that next time someone looks at it, there is context for why it's done this way.

2020-10-19 21:05 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppFragmentHTMLNotification.java
> +    //TODO: To delete this variable in future iterations
Sounds good!

2020-10-19 22:24 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableInAppMessage.java
> +    public static class InAppDisplaySettings {
I think html and padding can go together at similar level and we can reserve inAppDisplaySettings for higher functionalities.. (May be custom animation parameters in future).

2020-10-19 22:41 UTC, Ayyanchira commented on app/src/androidTest/java/com/iterable/iterableapi/MainActivityTest.java
> +        waitFor(500);
Other best alternative I found is waitFor(300) 

😁
Jokes apart.. 
This looked like a different case than our regular threading issues where we could flush background Threads.. 

May be I can looking optimizing it in tomorrow's test day

2020-10-20 17:34 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableWebViewClient.java
> +        view.setVisibility(View.GONE);
Why do we set it to `GONE` here?

2020-10-20 17:50 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableWebViewClient.java
> +        view.setVisibility(View.GONE);
Wow.. thank you so much! I dont think we need that code here. Totally forgot to remove this..

2020-10-20 18:10 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableWebView.java
> +        webViewClient = new IterableWebViewClient(notificationDialog);
You can also remove this, since we don't use `webViewClient` anymore.

2020-10-20 18:24 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableWebView.java
> +        webViewClient = new IterableWebViewClient(notificationDialog);
Missed out this one too... Thanks again

2020-10-22 02:22 UTC, vbabenkoru approved these changes

2020-10-22 16:01 UTC, Ayyanchira commented
🤩

2020-10-22 16:01 UTC, merged