[MOB-2002] - Request Processor - Online
Iterable/iterable-android-sdk pull request #287
Opened 2020-11-25 22:51 UTC by Ayyanchira

1. Introduced RequestProcessor interface
2. Implemented OnlineRequestProcessor which now creates IterableRequest and executes it
3. emails, userIds and authToken is now mainly fetched from authProvider from apiClient
4. changed/removed method signature for internal methods which had authToken or passed emailId or userId around
5  Changed IterablePushRegistration classes to accomodate authHandler changes
6. Changes in test method to make it pass.

2020-11-25 22:53 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> -    protected void registerDeviceToken(final @Nullable String email, final @Nullable String userId, final @Nullable String authToken, final @NonNull String applicationName, final @NonNull String devi
Why did you remove email/userId/authToken?

2020-11-25 22:54 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java
> +        RequestProcessor requestProcessor = new OnlineRequestProcessor();
Do we need to create the request processor every time?

2020-11-25 22:59 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java
> +        RequestProcessor requestProcessor = new OnlineRequestProcessor();
For now... Once we take parameters from config whether its online or offline, apiclient can create corresponding global request processor.

2020-11-25 23:06 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> -    protected void registerDeviceToken(final @Nullable String email, final @Nullable String userId, final @Nullable String authToken, final @NonNull String applicationName, final @NonNull String devi
I am thinking, now that we have authProvider, why not make only requestProcessor take email, userID and auth from that interface.
Also noticed that
1. public method only takes token.
2. we already have email, userId set before calling registerForPush

Although not sure why the line 435 method is protected.

2020-11-25 23:21 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> -    protected void registerDeviceToken(final @Nullable String email, final @Nullable String userId, final @Nullable String authToken, final @NonNull String applicationName, final @NonNull String devi
Hmm.. we should have regression tests for these. Basically, the reason we're passing email, userId and authToken here is because getting a token is asynchronous. By the time we get the token, the user identifiers might've changed.
Example:
* You set email to `null`
* It calls `disableDevice` to disable the token for the logged out user
* If we pass the current email/userId/authToken and then set email to `null`, we'll be able to call `disableDevice` with old auth even though the current one is all null
* If we don't store the auth with the token request, it will get the _current_ auth info from `authProvider`, which is already null, and will fail to disable the device.

2020-11-26 02:11 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> -    protected void registerDeviceToken(final @Nullable String email, final @Nullable String userId, final @Nullable String authToken, final @NonNull String applicationName, final @NonNull String devi
Added an integration/regression test here: #288.

2020-12-01 23:22 UTC, vbabenkoru commented on iterableapi/src/test/java/com/iterable/iterableapi/IterableApiIntegrationTest.java
> +public class IterableApiIntegrationTest extends BaseTest {
Rebase on latest master and maybe drop the merge commit to drop this change from the PR

2020-12-01 23:22 UTC, vbabenkoru commented on iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
> +    private IterablePushRegistration.IterablePushRegistrationImpl originalPushRegistrationImpl;
same, this should already be in master

2020-12-01 23:23 UTC, vbabenkoru requested changes
Looks like this needs cleanup to remove the already merged PR from the diff.

2020-12-02 03:29 UTC, vbabenkoru approved these changes

2020-12-02 07:11 UTC, merged