[MOB-2411] - Offline flag in config
Iterable/iterable-android-sdk pull request #298
Opened 2020-12-16 17:42 UTC by Ayyanchira

## 🔹 Jira Ticket(s) if any

https://iterable.atlassian.net/browse/MOB-2411

## ✏️ Description

1.  Added offlineProcessing boolean flag in config defaulted to false.
2. Added setRequestProcessor method in apiClient for IterableApi to be able to set offline mode after/during initializaiton.
3. In IterableAPI, if the flag is true, setRequestProcessor to offline.

Consequence: Had to make apiClient static and its required authProvider static as well.

2020-12-16 17:45 UTC, Ayyanchira commented
@vbabenkoru , the test `testSdkInitializedWithoutEmailOrUserId` fails now.
When run standalone, it succeeds.. 
Not understanding how the `apiclient` mock is getting invoked/interacted if email is set to null at the beginning.. Logically, it checks if sdkinitialrized -> email is null -> return false -> and nothing should have happened. But somehow, I dont know how, making apiClient static might have caused the problem. 🤔

2020-12-16 19:38 UTC, vbabenkoru commented
@Ayyanchira I think we should not make it static if there is any other way.

2020-12-16 19:40 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +            apiClient.setRequestProcessor(true, context);
I think this is confusing.. `setRequestProcessor(true, context)` - for a setter, I'd expect it to take some kind of a `RequestProcessor` class.. What `true` means in this case isn't clear.

2020-12-16 19:42 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableConfig.java
> +        public Builder setOfflineProcessing(@NonNull boolean offlineProcessing) {
This should be package-private for now, since it's not ready for production use yet.

2020-12-16 19:43 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +    static IterableApiClient apiClient = new IterableApiClient(new IterableApiAuthProvider());
Do we need to make this static?

2020-12-16 19:53 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +    static IterableApiClient apiClient = new IterableApiClient(new IterableApiAuthProvider());
Couldn't figure out a way around! 😕
Because `initialize` was a good place to setRequestProcessor; and because initialize was static, it was asking to make apiClient as static as well.

2020-12-16 22:27 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java
> +            this.requestProcessor = new OfflineRequestProcessor(IterableApi.getInstance().getMainActivityContext());
```suggestion
            this.requestProcessor = new OfflineRequestProcessor(authProvider.getContext());
```

2020-12-17 00:30 UTC, vbabenkoru requested changes

2020-12-17 00:30 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java
> +        //TODO: if api has to reinitialize, say after logout -> login, should apiClient also reset? In that case, there should be an else here. Or ApiClient should be reset on logout or some place
We don't need to reset apiClient on logout

2020-12-17 00:30 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java
> +    void enableOfflineProcessing(boolean offlineMode) {
`setOfflineProcessingEnabled`?

2020-12-17 00:30 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +        if (sharedInstance.config.offlineProcessing) {
The condition check is both here and inside `enableOfflineProcessing`. I think either the method should not have parameters, or we don't need the check here.

2020-12-18 05:02 UTC, vbabenkoru commented on iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
> +        verify(mockApiClient, times(1)).setOfflineProcessingEnabled(anyBoolean());
The test now checks for two things at the same time: that `setOfflineProcessingEnabled` was called and that no API requests are being made. I think ideally it shouldn't be explicitly checking for `setOfflineProcessingEnabled`.

2020-12-18 08:27 UTC, Ayyanchira commented on iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
> +        verify(mockApiClient, times(1)).setOfflineProcessingEnabled(anyBoolean());
That way we can be sure that it was only the setOfflineProcessingEnabled that was called. And not give free pass to other methods that could potentially get called if anything has to go wrong.

Also verify(mockApiClient).neededAMethod

2020-12-18 08:38 UTC, Ayyanchira commented on iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
> +        verify(mockApiClient, times(1)).setOfflineProcessingEnabled(anyBoolean());
Using `clearInvocation` 👍

2020-12-18 23:36 UTC, vbabenkoru approved these changes

2020-12-18 23:52 UTC, merged