[MOB - 2417] - CreatedAt and SentAt in requests
Iterable/iterable-android-sdk pull request #307
Opened 2021-01-14 22:59 UTC by Ayyanchira

## 🔹 Jira Ticket(s) if any

https://iterable.atlassian.net/browse/MOB-2417

## ✏️ Description

1. Changed date type from Date to long to store unix epoch time in milliseconds
2. Added sentAt dates in headers
3. Added check in test method to see if sentAt is sent in headers for all the requests
4. Added method in taskRunner to add createdAt in json data when making request back from database.

Pending -> Test method to see if createdAt is present in offline requests.

2021-01-21 02:48 UTC, vbabenkoru requested changes

2021-01-21 02:48 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableTask.java
> +    long createdAt;
If we change column types, I think we also should change the `CREATE TABLE` statement to specify numeric types for those columns in SQLite.

2021-01-21 02:48 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableTaskRunner.java
> +                //TODO: Any chances of request getting null?
Yes, but it will get caught by the statement just below this.

2021-01-21 02:48 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableTaskStorage.java
> +        //TODO: you might have to change the created to epoch literally while storing
What does this mean?

2021-01-21 02:48 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableTaskRunner.java
> +            jsonData.put(IterableConstants.KEY_CREATED_AT, task.createdAt);
Convert to seconds

2021-01-21 16:45 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableTaskStorage.java
> +        //TODO: you might have to change the created to epoch literally while storing
😬 😅 That was a note to myself to change the type from string to long in database 😅. Forgot to make that change.

2021-01-22 02:09 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableTaskStorage.java
> +            CREATED_AT + " LONG," +
Is that a valid column type in SQLite? Have you tried reinstalling the app or deleting the database and running this table creation query?

2021-01-22 19:33 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableTaskStorage.java
> +            CREATED_AT + " LONG," +
Yes. Tried. It says Numeric on datatype when looked into the table

2021-01-22 19:41 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableTaskStorage.java
> +            CREATED_AT + " LONG," +
Although, I will just have them as Numeric... why risk..

2021-01-22 20:40 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableTaskStorage.java
> +            CREATED_AT + " LONG," +
I was just reading the SQLite documentation on types, and the most appropriate seems to be `INTEGER` (or any of its aliases): https://www.sqlite.org/datatype3.html#affinity_name_examples

2021-01-22 20:41 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableTaskStorage.java
> +            CREATED_AT + " LONG," +
Didn't see `LONG` there so I'm wondering if it's something that may not be supported in current or past versions of SQLite on various devices.

2021-01-23 01:29 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableRequestTask.java
> +            if (jsonData.has(IterableConstants.KEY_CREATED_AT)) {
Why not just add it to `data` in `getTaskDataWithDate`? That way we won't need extra code here.

2021-01-23 01:30 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableTaskStorage.java
> +            CREATED_AT + " NUMERIC," +
See this comment: https://github.com/Iterable/iterable-android-sdk/pull/307#discussion_r562898987
I think this should be `INTEGER` or `BIGINT`.

2021-01-25 19:03 UTC, vbabenkoru approved these changes

2021-01-25 22:55 UTC, merged