[MOB-2437] - Get Remote Configuration
Iterable/iterable-android-sdk pull request #309
Opened 2021-01-20 19:04 UTC by Ayyanchira

## 🔹 Jira Ticket(s) if any

https://iterable.atlassian.net/browse/MOB-2437

## ✏️ Description

Get remote configuration for offline mode.
1. Call get remote configuration on Iterable API initialziation
2. On Success -> call the setOfflineProcessingEnabled
3. A type check to NOT reassign and reinitialize similar request processor.

2021-01-20 20:45 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +    void getRemoteConfiguration() {
`get` usually implies a getter that returns something to the caller. In this case, it doesn't return anything and processes the configuration itself. I think a better name might be something like `fetchRemoteConfiguration`.
Also I think we should persist the last fetched values and read them on launch, otherwise it will fallback to the default value every time.

2021-01-21 02:42 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +    void getRemoteConfiguration() {
Re: persistence, I see this is also something that's not in iOS, so it's not something that's necessary for this PR. I've opened a separate thread on Slack to discuss whether we need persistence for beta (both iOS and Android).

2021-01-22 02:05 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java
> +                if (this.requestProcessor == null || this.requestProcessor.getClass() != OfflineRequestProcessor.class) {
Maybe we should go further and two request processors should be lazily instantiated singletons, so we don't create another one when switching back and forth. Not likely to happen in reality, but still..

2021-01-22 02:07 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java
> +            //TODO: Add data and make request
?

2021-01-22 22:39 UTC, vbabenkoru requested changes

2021-01-22 22:39 UTC, vbabenkoru commented on iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
> +                "            // ....\n" +
Invalid JSON

2021-01-22 22:39 UTC, vbabenkoru commented on iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
> +
Add
```
        IterableActivityMonitor.getInstance().unregisterLifecycleCallbacks(getContext());
        IterableActivityMonitor.instance = new IterableActivityMonitor();
```

2021-01-22 22:39 UTC, vbabenkoru commented on iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
> +//        verify(mockApiClient).setOfflineProcessingEnabled(true);
Add at the end:
```                
        IterableActivityMonitor.getInstance().unregisterLifecycleCallbacks(getContext());
        IterableActivityMonitor.instance = new IterableActivityMonitor();
```

2021-01-22 23:48 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApiClient.java
> +                if (this.requestProcessor == null || this.requestProcessor.getClass() != OfflineRequestProcessor.class) {
Yeah. Looks like we will eventually have both offline and online request processor when it goes GA

2021-01-23 01:24 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +            fetchRemoteConfiguration();
I think this should be run once on launch (within the `if` block above), instead of on every foreground event.

2021-01-23 01:26 UTC, vbabenkoru commented on iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
> +                "                \"offlineModeBeta\": true,\n" +
Does this need extra indentation?

2021-01-25 05:00 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +            fetchRemoteConfiguration();
If it goes to if condition above it, the function will have to depend on autopushregistration flag as well. 
By having it here, looks like it wont be called on every foreground as its inside `if (!_firstForegroundHandled)` condition.

2021-01-25 05:01 UTC, Ayyanchira commented on iterableapi/src/test/java/com/iterable/iterableapi/IterableApiTest.java
> +                "                \"offlineModeBeta\": true,\n" +
adjusted. Thanks :)

2021-01-25 18:22 UTC, tapashmajumder commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +                    sharedInstance.apiClient.setOfflineProcessingEnabled(jsonData.getBoolean("offlineModeBeta"));
This doesn't seem to the right flag coming from the backend. It should be `SDKOfflineModeBeta`

2021-01-25 18:25 UTC, tapashmajumder commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +                    sharedInstance.apiClient.setOfflineProcessingEnabled(jsonData.getBoolean("offlineModeBeta"));
Oh. Wait

2021-01-25 18:26 UTC, tapashmajumder commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +                    sharedInstance.apiClient.setOfflineProcessingEnabled(jsonData.getBoolean("offlineModeBeta"));
You are right. Never mind.

2021-01-25 18:28 UTC, tapashmajumder commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +                    sharedInstance.apiClient.setOfflineProcessingEnabled(jsonData.getBoolean("offlineModeBeta"));
Nit: Not needed for +1. This is the correct flag. But we should probably load it from some constant file.

2021-01-25 18:29 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +                    sharedInstance.apiClient.setOfflineProcessingEnabled(jsonData.getBoolean("offlineModeBeta"));
Added them in constants in other PR where its getting stored persistently

2021-01-25 18:31 UTC, vbabenkoru commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableApi.java
> +            fetchRemoteConfiguration();
Ah, yeah, sorry, you're right! I missed the extra bracket and thought it was outside the conditional block.

2021-01-25 18:33 UTC, vbabenkoru approved these changes

2021-01-25 22:54 UTC, merged