[MOB-3386] android session tracking
Iterable/iterable-android-sdk pull request #393
Opened 2021-11-02 00:36 UTC by roninopf

## 🔹 Jira Ticket(s) if any

* [MOB-3386](https://iterable.atlassian.net/browse/MOB-3386)

## ✏️ Description

* opens and slightly refactors inbox session tracking related code
* also creates `updateVisibleRows` which does the [equivalent to the iOS SDK's version](https://github.com/Iterable/swift-sdk/blob/0dd3ce2f4e0a6904c51a67007a79c366a15b4a51/swift-sdk/Internal/InboxImpressionTracker.swift#L36)

2021-11-03 23:36 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/ImpressionData.java
> +public class ImpressionData {
Different files are good to keep it tidy but ImpressionData and SessionManager can stay package private. This should still be accessible to RN bridge through RNIterableInternal class.

2021-11-04 20:17 UTC, roninopf commented on iterableapi/src/main/java/com/iterable/iterableapi/ImpressionData.java
> +public class ImpressionData {
I tried removing `public` but it caused errors inside the native Android SDK. This doesn't seem to be the right approach?

2021-11-10 19:31 UTC, Ayyanchira requested changes
Added comment regarding ImpressionData being public

2021-11-10 21:46 UTC, roninopf commented on iterableapi/src/main/java/com/iterable/iterableapi/ImpressionData.java
> +public class ImpressionData {
Got it to work, my SDKs were probably out of sync the last time I tried

2021-11-10 21:56 UTC, Ayyanchira approved these changes

2021-11-10 22:31 UTC, merged