[MOB - 3970] - allow setShowBadge on notificationChannel
Iterable/iterable-android-sdk pull request #425
Opened 2022-02-02 23:01 UTC by Ayyanchira

## 🔹 Jira Ticket(s) if any

* [MOB-3970](https://iterable.atlassian.net/browse/MOB-3970)

## ✏️ Description

1. Introduced a notificationBadge boolean value in IterableConfig. This has default set to true. setting it to false will hide the nofitication badge on app icon.

Note:
Notification badge is applied to a channel. And this configuration can disable all the notification badge passed through Iterable.
It is a single boolean value. As Iterable supports multiple Android Notification Channels, it will make sense to enable and disable badging for selected channels.

2022-02-03 14:52 UTC, davidtruong requested changes
See change comments

2022-02-03 14:52 UTC, davidtruong commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java
> +                //TODO: Is it a good idea to have the value fetched from config like this? Or should we have the value passed through a utility method? which will basically do the same thing. OR stor
Let's chat about this later. We have multiple ways of passing in configurations. This way as well as the Android Manifest.

2022-02-03 14:52 UTC, davidtruong commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java
> +                notificationChannel.setShowBadge(IterableApi.getInstance().config.notificationBadge);
Unfortunately this won't work as is because the channel has already been created once on device and it is tied to a specific ChannelId.

That means for it to take affect on existing devices you would need to change the channelId to be different. 
IE: String channelId = context.getPackageName() + "_noBadge";

2022-02-03 18:22 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java
> +                //TODO: Is it a good idea to have the value fetched from config like this? Or should we have the value passed through a utility method? which will basically do the same thing. OR stor
Wow.. would like to explore how passing configurations through Manifest would work.

2022-02-03 18:22 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java
> +                notificationChannel.setShowBadge(IterableApi.getInstance().config.notificationBadge);
Hmm.. looks like it can work as long as the notificationChannel is not submitted to channel is submitted to [NotificationManager#createNotificationChannel(NotificationChannel)](https://developer.android.com/reference/android/app/NotificationManager#createNotificationChannel(android.app.NotificationChannel))

[Doc](https://developer.android.com/reference/android/app/NotificationChannel#setShowBadge(boolean))

But also one observation is ->
Once I - set it to false - , I had to uninstall and install the app with - set to true - to make the badges work again. Just changing the code and installing over the existing app did not make it work.

2022-02-03 20:40 UTC, davidtruong commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableNotificationHelper.java
> +                //TODO: Is it a good idea to have the value fetched from config like this? Or should we have the value passed through a utility method? which will basically do the same thing. OR stor
https://support.iterable.com/hc/en-us/articles/115000331943-Setting-up-Android-Push-Notifications-#customizing-android-push-notifications

We'll also need to update our support docs with the change after it is released.

2022-02-08 23:08 UTC, Ayyanchira commented
Closing this one. Implementing Android Manifest approach

2022-02-08 23:08 UTC, closed without merging