[MOB-5418] creates base package for flex messaging UI
Iterable/iterable-android-sdk pull request #489
Opened 2023-01-18 21:14 UTC by evangreer91

## 🔹 Jira Ticket(s) if any

* [MOB-5418](https://iterable.atlassian.net/browse/MOB-5418)

## ✏️ Description

This pull request creates the flex package in the iterable-ui module. The IterableFlexMessageActivity/IterableFlexMessageFragment will render the flex message UI and the IterableFlexViewActivity /ITerableFlexViewFragment will base the base UI component that renders the flex messages in other UI elements. I created a separate branch flex-ui-package to merge into off of the master branch.

2023-01-18 22:13 UTC, Ayyanchira requested changes
We might not need Activity or Fragment at all. This will need more detailed discussion before a foundation UI can be choosen

2023-01-25 18:55 UTC, Ayyanchira commented on iterableapi-ui/src/main/java/com/iterable/iterableapi/ui/flex/IterableFlexMessage.kt
> +package com.iterable.iterableapi.ui.flex
The Model class will have to reside in api package and not the ui package. So that customers willing to implement their own UI can access this

2023-01-25 18:58 UTC, Ayyanchira commented on iterableapi-ui/src/main/res/layout/iterable_flex_view_fragment.xml
> +            app:layout_constraintHorizontal_bias="0.064"
Horizontal bias looks very negligible, see if it can look just as okay without it. And the more we can avoid the magic numbers, the better.  :)

2023-01-25 18:59 UTC, Ayyanchira commented on iterableapi-ui/src/main/res/layout/iterable_flex_view_fragment.xml
> +            android:layout_height="49dp"
Looks good for this PR. But another level of details will be getting the ratio or height and width information from designers later if we are going to support out of the box ,ready to use templates.

2023-01-25 19:03 UTC, Ayyanchira reviewed
Added some comments. But overall a great PR. 
Also for image, we might have to think of a generic image which should indicate a no-image instead of coffee image. May be a question for designers to see what should we show if no image is passed. Just blank space? or something to denote no image...

2023-01-26 22:16 UTC, evangreer91 commented
> We might not need Activity or Fragment at all. This will need more detailed discussion before a foundation UI can be choosen

Resolved. The UI is implemented as a fragment that will be nested in a fragment on the application side.

2023-02-25 18:00 UTC, closed without merging

2023-02-25 18:01 UTC, evangreer91 commented
Closing this PR. We will have a pull request to merge with embedded-ui.