[MOB-6490] toggle off impression tracking if no embedded messages
Iterable/iterable-android-sdk pull request #601
Opened 2023-07-19 17:27 UTC by evantk91

## 🔹 Jira Ticket(s) if any

* [MOB-6490](https://iterable.atlassian.net/browse/MOB-6490)

## ✏️ Description

This pull request toggles off the impression tracking calls if there are no messages.

2023-07-19 18:20 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedManager.kt
> +        }
AddupdateHandler is where the activities and fragment tell the manager that it is eager to listen to the events..
By design, it might not be the best place to start a session. Or may be it work out best. However, this part should be separate from a session starting checking if the local message is empty or not. 
The check of whether to start a session based on localmessages should be a part of startSession method.

2023-07-19 18:35 UTC, Ayyanchira requested changes
Added some comments

2023-07-19 18:35 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedManager.kt
> +        }
Similar to above comments, endsession should get called regardless of localmessage queue. Messages could get deleted while the session is active. So it is important to not have external checks like message in memory check before calling endSession(). However, endSession can internally have its own checks like if the session had already started or not, if there were any impressions collected or not. And only then make the api request

2023-07-19 20:20 UTC, evantk91 commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedManager.kt
> +        }
Good point. I will restructure.

2023-07-19 20:37 UTC, evantk91 commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedManager.kt
> +        }
If we add the check to the start session internally we could need to pass in localMessages, do you think this is the best approach?

2023-07-19 20:38 UTC, Ayyanchira commented on iterableapi/src/main/java/com/iterable/iterableapi/IterableEmbeddedManager.kt
> +        }
May be for a session to start we wont need to look at local message queue. We can start session even with no messages. Its just that endSession will not end up making calls as there will be no impressions accumulated

2023-08-08 14:09 UTC, Ayyanchira approved these changes
LGTM

2023-08-08 16:18 UTC, evantk91 commented on iterableapi/build.gradle
> +    androidTestImplementation project(path: ':iterableapi')
Yeah prob making test fail :) I will remove

2023-08-08 18:21 UTC, merged